# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.   
collections:
  authors:

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      image: "small-pig.png"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      hero_height: is-half-height

title: Madhyama
email: contact@madhyama.io
description: >- # this means to ignore newlines until "baseurl:"
 In Sanskrit, the word Madhyama means middling or moderate. 
 As such, in an era of polarization, this forum was created 
 to represent a middling view between several of India’s 
 ideologies and philosophies. The goal of Madhyama is to 
 explore in depth, the marvelous intricacies of ancient Indic 
 philosophy, human/animal rights, and politics in the context of India. 
 Posts may be written by anonymous or identified authors, but 
 will always be heavily cited. The main rule of the forum is 
 that no individual post will justify violence towards other 
 human beings or other sentient beings, but otherwise viewpoints
 should be explored from several angles to provide a ‘middling’ viewpoint.
url: "https://www.madhyama.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Vikingprime
google_analytics: UA-121288020-1

theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme
favicon: assets/images/favicon.png
paginate: 8
paginate_path: "/blog/page:num"

disqus:
  shortname: "madhyama"

plugins:
  - jekyll-feed
  - jekyll-sitemap

max_posts_per_author: 4
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
